### ISSUE TITLE
Errors for no reason

### ISSUE THREAD

**Issue by REDitor** [REDitor/docker-template-phplatest#1]
Hi sir in my Week2/In_Class_Exercises/Guestbook_Database intellij is displaying errors at these variables:
![image](https://user-images.githubusercontent.com/71357600/142230255-36a7ebed-0aba-459a-a5b9-1086c19bac01.png)

However, everything is working fine. Should I do something about this or just ignore it?

**Comment by wimmelstein** [comment]
If everything is running fine then just ignore it. It's probably the syntax checker that doesn't see it It would be nicer to put ./dbconfig.php in there instead of dbconfig.php. And also, you don't want your dbconfig in the public folder. Put it a level higher and refer to it by ../dbconfig.php.

Let me know if we can close this.

**Comment by REDitor** [comment]
Yes I will close it thank you for the tip. I managed to finish the first part of the posts exercise and finishing the form right now. You can check it out if you are interested :)
